/*
 * V2X.h
 *
 * Created: 2/9/2016 11:28:54 AM
 *  Author: jbanks2
 */ 

#ifndef V2X_H_
#define V2X_H_

#ifdef OSX
#include <string.h>
#include <stdint.h>
#include <avr/iox128a3u.h>
#include "../ASF/xmega/utils/compiler.h"
#include "../ASF/xmega/drivers/nvm/nvm.h"
#include "../ASF/common/services/delay/delay.h"
#include "../ASF/common/boards/user_board/user_board.h"
#include "../ASF/common/boards/board.h"
#include "../ASF/common/boards/user_board.h"
#include "../ASF/common/drivers/nvm/common_nvm.h"
#include "../ASF/common/services/calendar/calendar.h"
#include "../ASF/common/services/clock/xmega/osc.h"
#include "../ASF/common/services/clock/xmega/pll.h"
#include "../ASF/common/services/clock/xmega/sysclk.h"
#include "../ASF/common/services/clock/genclk.h"
#include "../ASF/common/services/clock/osc.h"
#include "../ASF/common/services/clock/pll.h"
#include "../ASF/common/services/clock/sysclk.h"
#include "../ASF/common/services/cpu/reset_cause.h"
#include "../ASF/common/services/delay/xmega/cycle_counter.h"
#include "../ASF/common/services/delay/delay.h"
#include "../ASF/common/services/gpio/xmega_gpio/xmega_gpio.h"
#include "../ASF/common/services/gpio/gpio.h"
#include "../ASF/common/services/hugemem/avr8/hugemem.h"
#include "../ASF/common/services/hugemem/generic/hugemem.h"
#include "../ASF/common/services/hugemem/hugemem.h"
#include "../ASF/common/services/ioport/xmega/ioport.h"
#include "../ASF/common/services/ioport/xmega/ioport_compat.h"
#include "../ASF/common/services/ioport/ioport.h"
#include "../ASF/common/services/serial/xmega_usart/usart_serial.h"
#include "../ASF/common/services/serial/serial.h"
#include "../ASF/common/services/sleepmgr/xmega/sleepmgr.h"
#include "../ASF/common/services/sleepmgr/sleepmgr.h"
#include "../ASF/common/services/spi/xmega_spi/spi_master.h"
#include "../ASF/common/services/spi/spi_master.h"
#include "../ASF/common/services/storage/ctrl_access/ctrl_access.h"
#include "../ASF/common/services/usb/class/cdc/device/udi_cdc.h"
#include "../ASF/common/services/usb/class/cdc/device/udi_cdc_conf.h"
#include "../ASF/common/services/usb/class/cdc/usb_protocol_cdc.h"
#include "../ASF/common/services/usb/udc/udc.h"
#include "../ASF/common/services/usb/udc/udc_desc.h"
#include "../ASF/common/services/usb/udc/udd.h"
#include "../ASF/common/services/usb/udc/udi.h"
#include "../ASF/common/services/usb/usb_atmel.h"
#include "../ASF/common/services/usb/usb_protocol.h"
#include "../ASF/common/utils/interrupt/interrupt_avr8.h"
#include "../ASF/common/utils/stdio/stdio_serial/stdio_serial.h"
#include "../ASF/common/utils/stdio/stdio_usb/stdio_usb.h"
#include "../ASF/common/utils/interrupt.h"
#include "../ASF/common/utils/parts.h"
#include "../ASF/thirdparty/wireless/addons/sio2host/usb/sio2host.h"
#include "../ASF/xmega/drivers/ac/ac.h"
#include "../ASF/xmega/drivers/adc/adc.h"
#include "../ASF/xmega/drivers/cpu/ccp.h"
#include "../ASF/xmega/drivers/cpu/xmega_reset_cause.h"
#include "../ASF/xmega/drivers/dma/dma.h"
#include "../ASF/xmega/drivers/nvm/nvm.h"
#include "../ASF/xmega/drivers/pmic/pmic.h"
#include "../ASF/xmega/drivers/rtc/rtc.h"
#include "../ASF/xmega/drivers/sleep/sleep.h"
#include "../ASF/xmega/drivers/spi/spi.h"
#include "../ASF/xmega/drivers/tc/tc.h"
#include "../ASF/xmega/drivers/usart/usart.h"
#include "../ASF/xmega/drivers/usb/usb_device.h"
#include "../ASF/xmega/drivers/wdt/wdt.h"
#include "../ASF/xmega/services/pwm/pwm.h"
#include "../ASF/xmega/utils/assembler/gas.h"
#include "../ASF/xmega/utils/bit_handling/clz_ctz.h"
#include "../ASF/xmega/utils/preprocessor/mrepeat.h"
#include "../ASF/xmega/utils/preprocessor/preprocessor.h"
#include "../ASF/xmega/utils/preprocessor/stringz.h"
#include "../ASF/xmega/utils/preprocessor/tpaste.h"
#include "../ASF/xmega/utils/assembler.h"
#include "../ASF/xmega/utils/compiler.h"
#include "../ASF/xmega/utils/progmem.h"
#include "../ASF/xmega/utils/status_codes.h"
#include "../Config/conf_access.h"
#include "../Config/conf_adc.h"
#include "../Config/conf_board.h"
#include "../Config/conf_clock.h"
#include "../Config/conf_nvm.h"
#include "../Config/conf_rtc.h"
#include "../Config/conf_sio2host.h"
#include "../Config/conf_sleepmgr.h"
#include "../Config/conf_spi_master.h"
#include "../Config/conf_usart_serial.h"
#include "../Config/conf_usb.h"
#endif

#include <../asf.h>
#include "V2X_board.h"
#include "V2X_usb.h"
#include "V2X_Accel.h"
#include "V2X_button.h"
#include "V2X_control.h"
#include "V2X_gsm.h"
#include "V2X_init.h"
#include "V2X_led.h"
#include "V2X_power.h"
#include "V2X_spi.h"
#include "V2X_uart.h"
#include "V2X_menu.h"
#include "V2X_time.h"
#include "V2X_can.h"
#include "V2X_eeprom.h"
#include "V2X_car_state_check.h"

//#include "V2X_"

#endif /* V2X_H_ */